appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: I6jnxxzR3PTWbqX83cn7rP1JrVYhZuklPzVYhu3B/VjRyRHt8Ace5cm8HBgIZKzFf4DlAgCfIJ4bfE404tGm7IAAjsOlf8EwcTNeV/uZ18Bim7Vq0HRtztVhNDPHYmT1P9cEDHgsWBWjfAUXLmEb7SE+jpoYgJvRJDqjUGfSVlF/IgopH3834iEPo2UgVV5G9miqqXjhtYWU/3NTEnwUC2musF/19lqI6w+SUD8H50twEBKwFJVvXTaUA6WR/hZL0nCwsrQOqlN5vR4vBnJxPZxMCl0jxYPpSOjdhhYrcff/ue/QadpJQarURP8exQOa2aXChoUHc3T5/cSSvpPx9gisMaRjH9JIunOxgC/YsFdY8hRtHyJu3HYsLqrSf0k9+Jm1wVZ27wUvo84aRdB5RNSc5yHHO1MW5Hr8Btqa7n2UMNVw8IwgvP7PljDHRHV8UmYeQcNZUKZqSi9I484e/pkxzVerDRtD74YuyEHXv4ViYIuWgz5b3uoPksCMuc193V5SJPbv1kw4NYl7PyO3Il9NPRdqt7/ITVZduyC3MTwMAhbrCB0baGtvhRVsFu37H/X+NgeVZqfTmynYILIcDrvHNTxtYYcNXeYdy27EwJTpeErShIv3RSGz/7zaV6LapCdlf8OlGnkZvpwsFoiZkxpp8MC/jr+OG+xuYE2UA6I=}
bot:
  automerge: true
